spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: party-service
          uri: http://party-service:8084
          predicates:
            - Path=/party/**
          filters:
            - StripPrefix=1
        - id: oms-service
          uri: http://oms-service:8081
          predicates:
            - Path=/oms/**
          filters:
            - StripPrefix=1
        - id: wms-service
          uri: http://wms-service:8082
          predicates:
            - Path=/wms/**
          filters:
            - StripPrefix=1
        - id: mfg-service
          uri: http://mfg-service:8083
          predicates:
            - Path=/mfg/**
          filters:
            - StripPrefix=1
        - id: kafka-service
          uri: http://kafka-service:8085
          predicates:
            - Path=/kafka/**
          filters:
            - StripPrefix=1

eureka:
  client:
    enabled: false
