server:
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:partydb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: party-service
          uri: lb://party-service
          predicates:
            - Path=/party/**
          filters:
            - StripPrefix=1
        - id: oms-service
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
          filters:
            - StripPrefix=1
        - id: wms-service
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
          filters:
            - StripPrefix=1
        - id: mfg-service
          uri: lb://mfg-service
          predicates:
            - Path=/mfg/**
          filters:
            - StripPrefix=1
        - id: kafka-service
          uri: lb://kafka-service
          predicates:
            - Path=/kafka/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  auth:
    enabled: true
    secret: YXskSV6tKeQso3GjcnQV5mOVJHgkjWOrYUTrWjPlIWCFgJ3YdOcpN0VhsGLIVInl
    issuer: ${JWT_ISSUER:}
    allowed-skew-seconds: 60
    token-ttl-seconds: ${JWT_TTL_SECONDS:3600}
    ignored-paths:
      - /actuator/**
      - /eureka/**
      - /security/auth/**
