apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service
  template:
    metadata:
      labels:
        app: kafka-service
    spec:
      containers:
        - name: kafka-service
          image: spring-micro-service-erp/kafka-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: host.docker.internal:9094
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP
  selector:
    app: kafka-service
  ports:
    - port: 8085
      targetPort: 8085
