apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfg-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mfg-service
  template:
    metadata:
      labels:
        app: mfg-service
    spec:
      containers:
        - name: mfg-service
          image: spring-micro-service-erp/mfg-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_HOST
              value: host.docker.internal
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: mfgdb
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              value: "123456"
---
apiVersion: v1
kind: Service
metadata:
  name: mfg-service
spec:
  type: ClusterIP
  selector:
    app: mfg-service
  ports:
    - port: 8083
      targetPort: 8083
