apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-erp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-erp
  template:
    metadata:
      labels:
        app: ng-erp
    spec:
      containers:
        - name: ng-erp
          image: ng-erp:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ng-erp
spec:
  selector:
    app: ng-erp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # You can specify or leave it to auto-assign (30000â€“32767)
  type: NodePort
