server:
  port: 8082

spring:
  profiles:
    default: dev
  application:
    name: wms-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:wmsdb}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    packages-to-scan:
      - com.monash.erp.wms.entity
      - com.monash.erp.mfg.entity
  sql:
    init:
      mode: always
      data-locations: classpath:seed/*.sql,optional:classpath:demo/*.sql

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

oms:
  base-url: ${OMS_BASE_URL:http://localhost:8081}

wms:
  base-url: ${WMS_BASE_URL:http://localhost:${server.port}}
  service-token: ${WMS_SERVICE_TOKEN:}
